### ISSUE TITLE
Write To SD Card

### ISSUE THREAD

**Issue by jgbrown54** [Guizz27/Marlin---Longer-LKx-Pro#10]
You should enable #define SDCARD_CONNECTION ONBOARD in Configuration_adv.h to allow writing to an SD card. I have verified the functionality. Although Marlin kind of sucks. They only allow an 8 character filename and a 3 character extension like old DOS. But it does work. I have tested it with both gcodes and Repetier Host. It should work with any control software such as Pronterface. If you write the gcode file using a computer directly to the SD card you can use long filenames. The old 8.3 filename limitation is a limitation in Marlin.

**Comment by Guizz27** [comment]
thanks for the suggestion. I enabled it.
