### ISSUE TITLE
Compile of 2.0.9.4-GC-1.1 results in compile errors.

### ISSUE THREAD

**Issue by jgbrown54** [Guizz27/Marlin---Longer-LKx-Pro#13]
When compiling 2.0.9.4-GC-1.1 with no changes, I get the following compile errors.

Arduino: 1.8.19 (Windows 10), Board: "Arduino Mega or Mega 2560, ATmega2560 (Mega 2560)"

In file included from X:\Downloads\Longer LK5-Pro 3D Printer\Currently Installed Marlin 2.0.9.3\Marlin---Longer-LKx-Pro-2.0.9.4-GC-1.1\Marlin---Longer-LKx-Pro-2.0.9.4-GC-1.1\Marlin\src\lcd\e3v2\proui\gcode_preview.cpp:45:0:

X:\Downloads\Longer LK5-Pro 3D Printer\Currently Installed Marlin 2.0.9.3\Marlin---Longer-LKx-Pro-2.0.9.4-GC-1.1\Marlin---Longer-LKx-Pro-2.0.9.4-GC-1.1\Marlin\src\lcd\e3v2\proui\dwin_defines.h:45:4: error: #error "LIMITED_MAX_FR_EDITING is required with ProUI."

   #error "LIMITED_MAX_FR_EDITING is required with ProUI."

    ^~~~~

X:\Downloads\Longer LK5-Pro 3D Printer\Currently Installed Marlin 2.0.9.3\Marlin---Longer-LKx-Pro-2.0.9.4-GC-1.1\Marlin---Longer-LKx-Pro-2.0.9.4-GC-1.1\Marlin\src\lcd\e3v2\proui\dwin_defines.h:48:4: error: #error "LIMITED_MAX_ACCEL_EDITING is required with ProUI."

   #error "LIMITED_MAX_ACCEL_EDITING is required with ProUI."

    ^~~~~

X:\Downloads\Longer LK5-Pro 3D Printer\Currently Installed Marlin 2.0.9.3\Marlin---Longer-LKx-Pro-2.0.9.4-GC-1.1\Marlin---Longer-LKx-Pro-2.0.9.4-GC-1.1\Marlin\src\lcd\e3v2\proui\dwin_defines.h:51:4: error: #error "LIMITED_JERK_EDITING is required with ProUI."

   #error "LIMITED_JERK_EDITING is required with ProUI."

    ^~~~~

X:\Downloads\Longer LK5-Pro 3D Printer\Currently Installed Marlin 2.0.9.3\Marlin---Longer-LKx-Pro-2.0.9.4-GC-1.1\Marlin---Longer-LKx-Pro-2.0.9.4-GC-1.1\Marlin\src\lcd\e3v2\proui\dwin_defines.h:57:4: error: #error "INDIVIDUAL_AXIS_HOMING_SUBMENU is required with ProUI."

   #error "INDIVIDUAL_AXIS_HOMING_SUBMENU is required with ProUI."

    ^~~~~

X:\Downloads\Longer LK5-Pro 3D Printer\Currently Installed Marlin 2.0.9.3\Marlin---Longer-LKx-Pro-2.0.9.4-GC-1.1\Marlin---Longer-LKx-Pro-2.0.9.4-GC-1.1\Marlin\src\lcd\e3v2\proui\dwin_defines.h:60:4: error: #error "LCD_SET_PROGRESS_MANUALLY is required with ProUI."

   #error "LCD_SET_PROGRESS_MANUALLY is required with ProUI."

    ^~~~~

X:\Downloads\Longer LK5-Pro 3D Printer\Currently Installed Marlin 2.0.9.3\Marlin---Longer-LKx-Pro-2.0.9.4-GC-1.1\Marlin---Longer-LKx-Pro-2.0.9.4-GC-1.1\Marlin\src\lcd\e3v2\proui\dwin_defines.h:63:4: error: #error "STATUS_MESSAGE_SCROLLING is required with ProUI."

   #error "STATUS_MESSAGE_SCROLLING is required with ProUI."

    ^~~~~

X:\Downloads\Longer LK5-Pro 3D Printer\Currently Installed Marlin 2.0.9.3\Marlin---Longer-LKx-Pro-2.0.9.4-GC-1.1\Marlin---Longer-LKx-Pro-2.0.9.4-GC-1.1\Marlin\src\lcd\e3v2\proui\dwin_defines.h:66:4: error: #error "BAUD_RATE_GCODE is required with ProUI."

   #error "BAUD_RATE_GCODE is required with ProUI."

    ^~~~~

X:\Downloads\Longer LK5-Pro 3D Printer\Currently Installed Marlin 2.0.9.3\Marlin---Longer-LKx-Pro-2.0.9.4-GC-1.1\Marlin---Longer-LKx-Pro-2.0.9.4-GC-1.1\Marlin\src\lcd\e3v2\proui\dwin_defines.h:69:4: error: #error "SOUND_MENU_ITEM is required with ProUI."

   #error "SOUND_MENU_ITEM is required with ProUI."

**Comment by Guizz27** [comment]
Leaving a comment here for future reference.
When I merged Marlin 2.0.9.4, the Marlin repository had that Arduino IDE compilation error. It was fixed after I merged it. I decided to not merge again since Marlin 2.1 is now available.

If you feel 'i should still merge the fix into 2.0.9.4, let me know. I will close the issue, feel free to re-open.
