### ISSUE TITLE
Enable Linear Advance.

### ISSUE THREAD

**Issue by jgbrown54** [Guizz27/Marlin---Longer-LKx-Pro#15]
Enable LIN_ADVANCE with a default K of .22. The default value of .22 will have little affect on current users. But with the option enabled, users can adjust the value if they wish.

**Comment by jgbrown54** [comment]
I noticed that there is a setting on the Advanced screen to set the linear advance K factor but it won't do anything unless LIN_ADVANCE is enabled.

**Comment by Guizz27** [comment]
I enabled linear advance  but I set the default K value to 0 which is the same as deactivated but now the user can set the K value in the UI and save it to EEPROM.
