### ISSUE TITLE
RFI - Is it possibile to use a uart to connect marlin to octoprint avoiding usb ?

### ISSUE THREAD

**Issue by FulvioSpelta** [Guizz27/Marlin---Longer-LKx-Pro#16]
Sorry noob question. I'd like to connect my raspberry with octoprint to a U30 Pro (LGT KIT V1.0 motherboard) printer that is equipped with this firmware.

Is there some compilation directive that allows to enable communications using an uart ?
I'm using bltouch too.

Thanks for support.

**Comment by Guizz27** [comment]
Sorry, I don't know the answer. I use the USB port with my raspberry pi. 
I don't think Marlin supports 2 USB ports.
