### ISSUE TITLE
Implementation of Marlin 2.1.2.1

### ISSUE THREAD

**Issue by jgbrown54** [Guizz27/Marlin---Longer-LKx-Pro#21]

**Comment by Guizz27** [comment]
Thanks but I already integrated Marlin 2.1.2 on my computer and I do not plan to use the DWIN project anymore. I wrote a program to generate the DWIN_SET folder from text files. It makes it easier to add new features without having to open photoshop and DGUS software.
I'm still testing the changes and trying to add a few more features. I will still look at your changes and compare.

**Comment by jgbrown54** [comment]
I did miss a few things. So you can trash what I sent you. Do you want an update when I get it working?

**Comment by Guizz27** [comment]
I'm fine, I need to fix a couple small display issues.

**Comment by jgbrown54** [comment]
close
