### ISSUE TITLE
heating failed

### ISSUE THREAD

**Issue by loroff** [Guizz27/Marlin---Longer-LKx-Pro#25]
bonjours je viens d installer votre firmware tout fonctionne correctement mais 1 fois sur 2 au premier chauffage de l imprimante j  ai ce message qui apparait(: Heating failed, system stopped! Heater_ID: E0 -) j ai refait le pid plusieurs fois en prenant comme reference de temperature 210 degres mais le probleme persiste je presise qu avec le firmware d origine  je n avais pas le probleme merci pour votre reponse. voici une capture d ecran la fleche indique le moment precis ou le message apparait
![Capture](https://github.com/Guizz27/Marlin---Longer-LKx-Pro/assets/98763825/e8dda52b-5310-4fec-b2ea-0e88ef8f5182)

**Comment by Guizz27** [comment]
Vous avez fait une sauvegarde dans le EEPROM après le PID? Normalement, la température devrait légèrement dépasser la tempérture cible avant de redescendre.

C'est un message de octoprint? Est-ce que l'imprimante doit être redémarrer?

Si le message apparaît sur l'imprimante, il faut peut-être ajuster les configurations
  #define THERMAL_PROTECTION_PERIOD 40        // Seconds
  #define THERMAL_PROTECTION_HYSTERESIS 4     // Degrees Celsius

Une fois la température cible atteinte, il attend 40 secondes et la température ne devrait pas dévier de plus de 4 degrées. Selon le graph.

Si c'est Octoprint qui affiche le message alors il faudrait voir les plugins. Il semble que Octopod entre autre surveille la température et affiche une notification.

**Comment by Guizz27** [comment]
Vous pouvez aussi essayer les valeurs PID originales de Longer
  #define DEFAULT_Kp 22.2
  #define DEFAULT_Ki 1.08
  #define DEFAULT_Kd 114
ou M301 P22.2 I1.08 D114

**Comment by loroff** [comment]
bonjours je passe par repetier host pour modifier dans l eeprom je quitte et revient verifier si les valeur son bien rester de meme que via l ecran de mon imprimante les valeur on bien etait pris en compte 
octoprint me notifie que le firmware a envoyer un message d erreur et doit redemarrer ,de meme un message d erreur apparait sur l écran de l imprimante 
pour une cible de 210 degres la temperature arrive a 209 puis redescend vers 200 avant de remonté le messages apparait lorsque je suis proche de 200 degres (je possede egalement une tete avec 2 ventilateur de filament )
je precise qune fois la temperature atteinte elle ne fluctue pas du tout 
sur votre conseil je vais essayer les valeurs pid d origine de longer et faire plusieurs essaies
j  ai fait l essai avec les valeur d origine mais le probleme est toujours la

**Comment by Guizz27** [comment]
je ferai des tests cette fin de semaine

**Comment by loroff** [comment]
![Capture2](https://github.com/Guizz27/Marlin---Longer-LKx-Pro/assets/98763825/d3e94247-64c3-4fcb-a60f-516dfda5a7e9)
peu etre une piste effectivement ici .les valeur de mon firmeware d avant marlin2.0 par contre je ne sais pas du tout comment faire pour rentrer dans l imprimante

**Comment by loroff** [comment]
![225254](https://github.com/Guizz27/Marlin---Longer-LKx-Pro/assets/98763825/70623b1d-fc71-4ec2-a120-e7a094e83f4b)
bonjours je precise que ma lk4 pro possede cette tete double ventilateur .peu etre le probleme viendrait de la le refroidissement de la tete  est peu etre different des lk4 normal
![Capture PNG7373](https://github.com/Guizz27/Marlin---Longer-LKx-Pro/assets/98763825/f8ddfc1a-9767-4726-b5e7-021693f44798)

**Comment by loroff** [comment]
[octoprint (2).log](https://github.com/Guizz27/Marlin---Longer-LKx-Pro/files/14573727/octoprint.2.log)
voici un log ou le defaut apparait

**Comment by Guizz27** [comment]
Est-ce que le problème survient pendant l'impression? Normalement, ces ventilateurs ne tournent pas avant le début de l'impression et généralement pas avant la deuxième couche.

Effectivement dans le log, il ne semble pas être capable de chauffer la buse assez rapidement.

Si c'est pendant l'impression, tu peux essayer de faire le PID avec les ventilateurs en marche.

Aussi, le log montre que c'est bel et bien l'imprimante qui fait l'erreur. Je pensais que Octoprint aurait pu générer l'erreur.

Aussi, il faut noter que le "P" de PID est surtout utilisé lorsque que la température est loin de la cible tandis que le "I" sert surtout quand la température est proche de la cible.

Dans ce cas la température est à environ 188C donc 12C de la cible. Peut-être que le mix de P et I fait en sorte qu'il ne chauffe pas assez vite. Par exemple, si tu attends que la température est à 150C avant de mettre la cible à 200C il va probablement chauffer plus vite.

C'est quand même intéressant. Je vais faire le test avec des température semblables à ton log.

**Comment by Guizz27** [comment]
Je viens de faire un test. J'ai chauffé à 200C. Ensuite j'ai laissé refroidir vers 185-190C et j'ai remis une cible à 200C. Ça pris pas plus de 15 secondes avant d'atteindre le 200C.
C'est quoi les veleurs de ton PID?

**Comment by loroff** [comment]
> Est-ce que le problème survient pendant l’impression ? Normalement, ces ventilateurs ne tournent pas avant le début de l’impression et généralement pas avant la deuxième couche.
bonjours non le probleme ne survient jamais pendant l impression  seulement au moment de la chauffe ou lorsque j enchaine plusieurs impression

**Comment by loroff** [comment]
bonjours 
-le probleme ne survient jamais pendant l impression seulement  lors de la chauffe ou quand j enchaine plusieurs impression (l impression terminé les chauffes se coupent et moi je remet en chauffe pour l impression suivante).
-au moment de la chauffe seul le ventilateur de hotend tourne les deux autre sont eteint.
-oui j ai essayé avec répetier-host et le probleme est toujours present.
-les valeur de pid actuelles sont :  P 14.62
                                                      I 0.75
                                                      D 71.59

**Comment by loroff** [comment]
je viens de faire le meme test chauffe a 200 degres j ai laisser refroidir a 185 puis remis la chauffe ,resultat le message d ereur est apparut au bout de 19 secondes et mon ma buse n etait qua 184 degres

**Comment by loroff** [comment]
jai fait le meme test chauffe a 200 puis refroidissement vers 185,puis remis cible a 200 le message d erreur est apparut au bout de 19 secondes et je n etait  qu a187 degres

**Comment by loroff** [comment]
![oui](https://github.com/Guizz27/Marlin---Longer-LKx-Pro/assets/98763825/f002e586-faef-42a1-b469-7ea3d40b2cfa)
je vais peu etre dire une betise mais cela peu venir de la ?

**Comment by loroff** [comment]
![oui](https://github.com/Guizz27/Marlin---Longer-LKx-Pro/assets/98763825/a9693f94-0e4a-41f3-af80-9a9c7cf3dcc2)
je vais peu etre dire une betise le probleme ne viendrait pas d une valeur de "watch_temp_period "trop faible ?

**Comment by Guizz27** [comment]
Ma version locale est à 40 secondes. Probablement que ça été augmenté dans Marlin 2.1.2.1.
Tu peux le compiler avec 40 secondes.

**Comment by loroff** [comment]
Désolé je ne sais pas comment on fait

**Comment by Guizz27** [comment]
Je peux fournir la dernière version que j'ai et qui n'est pas encore sur github.
C'est LK4 ou LK5 et avec ou sans bl touch?

La dernière version pourrait avoir des problèmes. Je la roule chez moi depuis des mois.

**Comment by loroff** [comment]
il  me semblerai avoir resolut le probleme en essayant votre methode : faire le pid en mettant en marche egalement les ventilateurs de buse .je n ai pas reussit a reproduire le defaut

**Comment by loroff** [comment]
pour ma part il s agit d une lk4 pro sans bltouch

**Comment by Guizz27** [comment]
Si ca fonctionne pour l'instant c'est tant mieux.
Pour ma version que j'ai à la maison je sais qu'il y a un problème je crois quand on fait "pause" sur l'écran et ensuite on "Abort". C'est pour l'instant le seul problème que j'ai remarqué.

Mais c'est mieux de garder votre version si le problème ne se produit plus.

**Comment by loroff** [comment]
ok merci pour cette excellent travail j attend votre prochaine version .

**Comment by loroff** [comment]
bon j ai parlé un peu trop vite ,toujours quelques messages d erreur au moment ou je remet la chauffe entre 2 impressions l une derriere l autre je pense que je vais essayer de passer  le "WATCH_TEMP_PERIOD " d une valeur de 20 secondes a 40 secondes.
pouvez vous me dire si les ligne  95 a 109 sont correctement commenté ou decommenté pour une lk4 pro sans bltouch merci.
![54545451](https://github.com/Guizz27/Marlin---Longer-LKx-Pro/assets/98763825/502c6dca-7ce1-4f6e-ad55-eb5651296927)

**Comment by Guizz27** [comment]
oui les lignes sont correctes

**Comment by loroff** [comment]
petit retour pour signaler que la modif de "WATCH_TEMP_PERIOD" a fonctionné  vous pouvez fermer le sujet merci

**Comment by Guizz27** [comment]
Merci
