### ISSUE TITLE
Display two decimals in current Z.

### ISSUE THREAD

**Issue by thghca** [Guizz27/Marlin---Longer-LKx-Pro#6]
For now current print height is not very useful with some layer heights.
Printer can handle fine 0.04*n layer height. With certain heights we lose significant numbers.
Z offset also with point two decimals.

Also unlike marlin repo this repo has no new issue (bug/feature request) links.

**Comment by Guizz27** [comment]
I believe the "new issue" link should be available. Thanks for the idea about the 2 decimals.

**Comment by Guizz27** [comment]
The new release 2.0.8.1-G1RC3 now displays the height with 2 decimals. thanks again for the idea.
