### ISSUE TITLE
DGUS file update for Marlin 2.0.9.3

### ISSUE THREAD

**Issue by boromyr** [Guizz27/Marlin---Longer-LKx-Pro#7]
Hi, I adapted your modification to dgus reloaded to work with the latest version of Marlin. It should work fine for all pages, the only problem is the print pause which I think doesn't work well, plus the offset z during printing, but that's not Marlin's problem
[dgus_reloaded.zip](https://github.com/Guizz27/Marlin---Longer-LKx-Pro/files/7942444/dgus_reloaded.zip)
.

**Comment by Guizz27** [comment]
Thank you very much! I have integrated Marlin 2.0.9.3 on my local copy but I haven't had time to test it and refresh the github repository. I will compare what you did with my version. I may catch issues on my version before I test it.

**Comment by boromyr** [comment]
It's provable there are some bugs that I haven't found, I merged with WinMerge trying to keep your additional functions and updated the *_F serial macros that were giving compile errors, so it's an alpha version. Also, Marlin added some fixes to dgus_reloaded that I didn't have time to add. I fixed some syntax errors for Junction Deviation and Linear Advance.  

Off Topic: In the screen firmware there is the source file in Photoshop that I opened with Krita and I saw that there are many layers on the main background, I wanted to ask you if you used a script or a multiple export function. I would simply like to change the background, but I don't want to export all the pages individually.

**Comment by Guizz27** [comment]
I have an action in Photoshop called "saveall" that will activate layers and save for each screen. Before running it, only the background layers should be visible. I recorded that action once by exporting each screen one by one.

**Comment by boromyr** [comment]
Could you share it? I've never used Photoshop, but I think I understand it's a script or macro. I'd appreciate it.

**Comment by Guizz27** [comment]
Here is the file in a zip
[LK4Pro.zip](https://github.com/Guizz27/Marlin---Longer-LKx-Pro/files/8008002/LK4Pro.zip)

**Comment by boromyr** [comment]
Thank you very much

**Comment by boromyr** [comment]
@Guizz27 I saw that you updated the reposity files, did you make any corrections or changes? In that case I will update my files as well.

**Comment by Guizz27** [comment]
It's the Marlin 2.0.9.3 integration including some of your changes. There is more than the lcd code to integrate for pause and powerloss recovery for example. My repository is still a few commits behind Marlin. I will do another integration soon. 
There are no new features or fixes. I'm working on a tool to help for the screens. Once I have this tool, I will add more features.

**Comment by boromyr** [comment]
Ok thanks, so for now I continue to use my files until your next updates.

**Comment by Sawurai80** [comment]
buonasera, ho compilato marlin 2.0.9.3 per la mia lk4 pro no bltouch e mi sono accorto che la regolazione dello Z-off durante la stampa da due problemi: se si regola con le frecce si verifica lo spostamento di z ma non viene incrementato il suo valore sullo schermo, se invece si vuole inserire il valore attraverso il pannello di input, quest'ultimo si apre ma in maniera incompleta...potresti gentilmente aiutarmi a risolvere il problema?

**Comment by boromyr** [comment]
Just today I opened the screen firmware for the z offset problem when printing, but it seems to be correct, in the simulation the numpad opens and closes correctly.

**Comment by Sawurai80** [comment]
potresti gentilmente linkarmi il file firmware dello schermo? te ne sarei veramente grato.
il mio problema è questo:
![image](https://user-images.githubusercontent.com/100000363/154770264-6a201393-c5b9-4380-80ff-103eb48297ab.png)

**Comment by Sawurai80** [comment]
potrebbe dipendere dalla compilazione errata di marlin?

**Comment by boromyr** [comment]
No Marlin has nothing to do with it, the screen has its MCU and its memory, the graphics are managed internally. The screen source is [here](https://github.com/Guizz27/DWIN_LK4Pro), but you need DGUS 7.3 to open it.

**Comment by Sawurai80** [comment]
cosa conviene che io faccia? grazie ancora per la tua disponibilità

**Comment by Sawurai80** [comment]
risolto il problema della schermata incompleta ... ho riformattato la SD e flahato il DWIN SET dentro la cartella release... ma rimane il problema che qualsiasi valore inserisco su adjustament z-offset il valore sulla schermata rimane sempre 0.

**Comment by Guizz27** [comment]
This control sets the Z-offset. If modified while printing it will adjust it using baby stepping.
Since you don't have a BLTouch, the value displayed is always 0. Also, anything you enter is ignored.

In a future release I could make baby stepping available to non-BLTouch users.

**Comment by boromyr** [comment]
Did you solve the problem by simply reloading the firmware again?

**Comment by Sawurai80** [comment]
ciao ragazzi ... ho formattato lentamente la SD in FAT32 e 4096 byte, poi ho inserito la cartella DWIN da release e infine ricaricato il firmware sul display. così la schermata di input numpad si è aperta correttamente.

**Comment by boromyr** [comment]
Great thanks then I'll try too!

**Comment by Sawurai80** [comment]
> Questo controllo imposta l'offset Z. Se modificato durante la stampa, lo regolerà usando il baby stepping. Dal momento che non hai un BLTouch, il valore visualizzato è sempre 0. Inoltre, tutto ciò che inserisci viene ignorato.
> 
_> In una versione futura potrei rendere disponibile il baby stepping agli utenti non BLTouch._


il babystepping per gli utenti non BLTouch sarebbe veramente una grande cosa!!!! potresti gentilmente lavorarci su??
grazie in anticipo.

**Comment by boromyr** [comment]
On thingvierse there is an adapter to mount endstop Z instead of bltouch and emulate it, you could try this alternative. Theoretically, you can enable bltouch in marlin by leaving endstop Z where it is, you will be able to homing and babysteps, but you will not be able to use ABL.

**Comment by Guizz27** [comment]
> il babystepping per gli utenti non BLTouch sarebbe veramente una grande cosa!!!! potresti gentilmente lavorarci su?? grazie in anticipo.

I will work on it but I'm busy and won't be able to work on it for a little while.

**Comment by Sawurai80** [comment]
> On thingvierse there is an adapter to mount endstop Z instead of bltouch and emulate it, you could try this alternative. Theoretically, you can enable bltouch in marlin by leaving endstop Z where it is, you will be able to homing and babysteps, but you will not be able to use ABL.

gentilmente potresti indicarmi qual'è l'adattatore e come procedere per fare questo? grazie mille

**Comment by boromyr** [comment]
I don't know why I didn't save it, you should do a keyword search, like: "bltouch endstop z replace". The main image I think was an Ender 3 extruder with this white support. The instructions on how to proceed I believe are in the description.

**Comment by Sawurai80** [comment]
![DEE3FAF3-0A8A-43A5-B7C9-C080738A4F23](https://user-images.githubusercontent.com/100000363/154971677-db902a8f-8771-4d3e-85f2-1613c6e480b1.png)
È per caso questo?

**Comment by boromyr** [comment]
Exactly, with this you can probe the bed, and you can also use the screen firmware for bltouch

**Comment by Sawurai80** [comment]
grazie mille di tutto! vi aggiornerò sui risultati

**Comment by jgbrown54** [comment]
When compliing Marlin for an LK5 without BLTouch, I get an error saying DGUS requires a bed probe. Is there a version for manual leveling?

**Comment by Guizz27** [comment]
Sorry, after integrating 2.0.9.3 the compilation without BLtouch was broken. I just committed a fix. The change is in the file src/inc/SanityCheck.h. I tested that it compiles correctly, I didn't test if the code works on the printer since the code is the same as the one I did a while ago to support non-BLtouch printers.

**Comment by jgbrown54** [comment]
Does it work both with and without BLTouch? What will happen if they select Auto on the Leveling screen?

**Comment by Guizz27** [comment]
Yes it works for both. Without a BLtouch, when you select Leveling in the settings menu it goes directly to the 5-point manual leveling screen. The user will not see options for auto leveling and Z-offset.

Here is the piece of code that handles that:
#if !HAS_LEVELING
  // Skip Leveling menu if no automatic leveling
  if (screen == DGUS_Screen::LEVELING_MENU) {
    if (dgus_screen_handler.GetCurrentScreen() == DGUS_Screen::SETTINGS_MENU) {
      screen = DGUS_Screen::LEVELING_MANUAL;
    }
    else {
      screen = DGUS_Screen::SETTINGS_MENU;
    }
  }
#endif

Without a BLTouch, the Print Adjust screen still has a Z-offset option at the bottom you would normally use to adjust during the first layer, this option is there but does nothing for non-bltouch. In a future version, I will make sure it works.
