### ISSUE TITLE
Compiling with Linear advance

### ISSUE THREAD

**Issue by Roman7603** [Guizz27/Marlin---Longer-LKx-Pro#9]
**Describe the bug**
I found a little bug in two lines:

Marlin\src\lcd\extui\dgus_reloaded\DGUSRxHandler.cpp:1197:10: error: 'setLinearAdvance_mm_mm_svalue' is not a member of 'ExtUI'
correct is
ExtUI::setLinearAdvance_mm_mm_s(value, ExtUI::extruder_t::E0);

Marlin\src\lcd\extui\dgus_reloaded\DGUSTxHandler.cpp:726:124: error: expected ',' or ';' before ')' token
correct is:
const int16_t data = dgus_display.ToFixedPoint<float, int16_t, 2>(ExtUI::getLinearAdvance_mm_mm_s(ExtUI::extruder_t::E0));

After corrections is everything ok

Thank You for your perfect work and time!

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Guizz27** [comment]
Thank you very much. I made the fix for the compilation. :)
